name = "Cloak of Billowing"
type = "cloak, common"
requires_attunement = false
image_path = ""
skip = false
description = """
While wearing this cloak, you can use a bonus action to make it billow dramatically.
"""