name = "Hat of Vermin"
type = "hat, common"
requires_attunement = false
image_path = "hat_of_vermin.png"
description = """
This hat has 3 charges. While holding the hat, you can use an action to expend 1 of its charges and speak a command word that summons your choice of a bat, a frog, or a rat. It behaves as an ordinary creature of its kind and disappears after 1 hour or when it drops to 0 hit points. The hat regains all expended charges daily at dawn.
"""
