name = "Illuminators Tattoo"
type = "wondrous item, common"
requires_attunement = true
image_path = "illuminators_tattoo.jpg"
description = """While this tattoo is on your skin, you can write with your fingertip as if it were an ink pen that never runs out of ink.

As an action, you can touch a piece of writing up to one page in length and speak a creature's name. The writing becomes invisible to everyone other than you and the named creature for the next 24 hours. Either of you can dismiss the invisibility by touching the script (no action required). Once used, this action can't be used again until the next dawn."""