name = "Mystery Key"
type = "wondrous item, common"
requires_attunement = false
image_path = "mystery_key.jpg"
description = """A question mark is worked into the head of this key. The key has a 5 percent chance of unlocking any lock into which it's inserted. Once it unlocks something, the key disappears."""