name = "Pipe of Smoke Monsters"
type = "wondrous item, common"
requires_attunement = false
image_path = ""
skip = false
description = """
While smoking this pipe, you can use an action to exhale a puff of smoke that takes the form of a single creature, such as a dragon, a flumph, or a froghemoth. The form must be small enough to fit in a 1-foot cube and loses its shape after a few seconds, becoming an ordinary puff of smoke.
"""