name = "Potion of Growth"
type = "potion, uncommon"
requires_attunement = false
image_path = "potion_of_growth.jpeg"
skip = false
description = """The red in the potion's liquid continuously expands from a tiny bead to color the clear liquid around it and then contracts. Shaking the bottle fails to interrupt this process. When you drink this potion, you gain the "enlarge" effect of the enlarge/reduce spell for 1d4 hours (no concentration required)."""