name = "Ring of Force Shield"
type = "ring, uncommon"
image_path = "ring_of_force_shield.png"
skip = true
description = """While wearing this ring, you can cast shield of faith as a bonus action on yourself, gaining a +2 bonus to AC for 10 minutes. Once used, the ring can't be used again until the next dawn."""