name = "Trident of Warning"
type = "weapon, uncommon"
requires_attunement = true
image_path = "trident.png"
skip = false
description = """This magic trident warns you of danger. While the trident is on your person, you have advantage on initiative rolls. In addition, you and any of your companions within 30 feet of you can't be surprised, except when incapacitated by something other than nonmagical sleep. The trident magically awakens you and your companions within range if any of you are sleeping naturally when combat begins."""