name = "Viol of Illusions"
type = "instrument, common"
requires_attunement = true
image_path = "viol_of_illusions.jpg"
skip = false
description = """
While you are playing this musical instrument, you can create harmless, illusory visual effects within a 5-foot-radius sphere centered on the instrument. If you are a bard, the radius increases to 15 feet. Sample visual effects include luminous musical notes, a spectral dancer, butterflies, and gently falling snow. The magical effects have neither substance nor sound, and they are obviously illusory. The effects end when you stop playing.
"""