name = "Immovable Rod"
type = "rod, uncommon"
requires_attunement = false
image_path = "immovable_rod.png"
description = """
You can use an action to press the button on this rod to cause the rod to become magically fixed in place. Until you or another creature uses an action to push the button again, the rod doesn't move, even if it is defying gravity. The rod can hold up to 8,000 pounds of weight.
"""